---
- hosts: webservers
  become: yes
  tasks:
   - name: Installation apache
     yum: name=httpd state=latest update_cache=yes
   - name: restarting and enable the apache2
     service: name=httpd state=started enabled=yes
